(part "UJC-H-G-SMT-2-P6-TR"
    (packageRef "UJCHGSMT2P6TR")
    (interface
        (port "1" (symbPinId 1) (portName "MH1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "MH2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "MH3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "MH4") (portType INOUT))
        (port "A5" (symbPinId 5) (portName "CC1") (portType INOUT))
        (port "A9" (symbPinId 6) (portName "VBUS_1") (portType INOUT))
        (port "A12" (symbPinId 7) (portName "GND_1") (portType INOUT))
        (port "B5" (symbPinId 8) (portName "CC2") (portType INOUT))
        (port "B9" (symbPinId 9) (portName "VBUS_2") (portType INOUT))
        (port "B12" (symbPinId 10) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "179-UJCHGSMT2P6TR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Same-Sky/UJC-H-G-SMT-2-P6-TR?qs=IKkN%2F947nfApFV8T6rOqww%3D%3D")
    (property "Manufacturer_Name" "Same Sky")
    (property "Manufacturer_Part_Number" "UJC-H-G-SMT-2-P6-TR")
    (property "Description" "Type C, Power Only, 30 Vac, 3 A, Horizontal, Gold plated 1u, Surface Mount,6 pin, USB Receptacle")
    (property "Datasheet_Link" "https://www.sameskydevices.com/product/resource/ujc-h-g-smt-2-p6-tr.pdf")
    (property "symbolName1" "UJC-H-G-SMT-2-P6-TR")
)
