M48
; DRILL file {KiCad 9.0.1} date 2025-04-18T19:18:50+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-18T19:18:50+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X2.7134Y-1.1256
X2.7134Y-4.6689
X6.6504Y-1.1256
X6.6504Y-4.6689
T2
X5.0105Y-4.6887
M30
