M48
; DRILL file {KiCad 8.0.8} date 2025-04-11T18:10:54+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-11T18:10:54+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.0105Y-4.6887
T2
X2.7693Y-4.6398
X2.772Y-0.9039
X6.7118Y-0.9039
X6.7118Y-4.6398
M30
